### ISSUE TITLE
Investigate UI toast for cookies

### ISSUE THREAD

**Issue by oed** [3box/3box#1064]
Potentially in 3box-js or 3id-connect? Or both?

**Comment by zachferland** [comment]
its just going to be 3boxjs, also its really only indexeddb required (maybe localstorage now), but not sure what has to do with cookies (other than that mode probably limited other storage layers)

**Comment by dazuck** [comment]
@kamescg sync with zach

**Comment by kamescg** [comment]
The cookie part as far as I could tell was somehow linked to localstorage on Brave. But from what I can tell Portis is being injected, which also injects a cookie, which might have caused the cookie warning for them?

At first I thought it Web3Modal, but it looks like it might be the 3Box modules. Even reported a ticket with them lol.

https://github.com/Web3Modal/web3modal/issues/159

Working replicating the problem fully and will report back.

**Comment by zachferland** [comment]
3id-connect is removing the providers, so meeting any of the specific provider requirements will be up to apps/providers again, but right now with portis that sounds about right 

in 3boxjs, should just be that indexeddb is strictly required

**Comment by kamescg** [comment]
I was having issues with Brave, so just started to debug with Chromium. 

When disabling cookies I was no longer able to access localStorage, so it seems the two are actually linked.

Below is error message I received when attempting to connect to a fresh account.

The tough part is I can edit localStorage from an installed module, because it's not actually a cross-site origin problem, so it's only when sending a request to the https://connect.3box.io/index.js file are problems going to occur.

What file is getting requested at that address?

```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Object.<anonymous> (https://connect.3box.io/index.js:214:6257)
    at r (https://connect.3box.io/index.js:170:124171)
    at Object.<anonymous> (https://connect.3box.io/index.js:185:5197)
    at r (https://connect.3box.io/index.js:170:124171)
    at Object.<anonymous> (https://connect.3box.io/index.js:190:33414)
    at r (https://connect.3box.io/index.js:170:124171)
    at Object.<anonymous> (https://connect.3box.io/index.js:190:33156)
    at r (https://connect.3box.io/index.js:170:124171)
    at https://connect.3box.io/index.js:170:124970
    at Object.<anonymous> (https://connect.3box.io/index.js:170:124980)
```

![image](https://user-images.githubusercontent.com/3408362/81968595-7319de00-95d1-11ea-8217-20edd88ca868.png)

**Comment by zachferland** [comment]
Ah ok, so yeah suspected cooking disabling also disabled localstorage (at least in iframe)

That is 3id-connect and appears that the browser policy is to disable storage in third party iframe windows. a few browsers do this, apple/safari already dont allow indexeddb in iframe anywhere. 

we can likely get 3id-connect to work with out any localstorage access, but only worth doing, if indexeddb is available still when cookies/storage disabled (in main window)

**Comment by kamescg** [comment]
To keep things simple (and solve the issue for UnstoppableDomains asap) for now might be easiest to just display an alert modal asking user's to enable cookies for the current site from the iFrame?

Possible to easily setup a dev version of `https://connect.3box.io/index.js` so I can test it out with a custom build?

**Comment by zachferland** [comment]
are they using 3id connect? or this error just throws on page load
- if not using, then i can make sure 3idconnect doesnt throw when not used
- and if while using, could have alert modal for quick fix, but ill probably have to add something for the parent window to check if available in iframe on page load, since waiting for interaction may be a bit late in cycle of interaction 

right now can run in https://github.com/3box/3id-connect, npm run start, and will server locally
unfortunately 3id connect url hard coded in 3boxjs, would have to change that to point locally (but easy if you got that repo and running the 3box example there)
soon we will have it https://github.com/3box/3box-services-box
